version: "3.1"

services:
    webserver:
      image: nginx:stable-alpine
      container_name: app-laravel-nginx
      working_dir: /var/www/app
      ports:
        - "${APP_PORT}:80"
      volumes:
        - ../backend:/var/www/app
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    app:
      build: ./php-fpm
      container_name: app-laravel-php
      working_dir: /var/www/app
      volumes:
        - ../backend:/var/www/app
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    mysql:
      image: mysql:5.7.22
      container_name: app-laravel-mysql
      command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
      working_dir: /var/www/app
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=tests
        - MYSQL_USER=user
        - MYSQL_PASSWORD=123

    beanstalkd:
      image: schickling/beanstalkd
      container_name: app-laravel-beanstalkd
